# Generated by Django 5.0.6 on 2024-06-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_banner_path',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image_logo_path',
            field=models.TextField(blank=True),
        ),
    ]
