# Generated by Django 5.0.6 on 2024-07-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image_banner_path_project_image_logo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='choices',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.TextField(blank=True),
        ),
    ]
