# Generated by Django 5.0.6 on 2024-07-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_choices_project_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
