# Generated by Django 5.0.6 on 2024-07-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ls_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
