# Generated by Django 5.0.6 on 2024-06-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('context', models.TextField(blank=True)),
                ('business_section', models.CharField(max_length=300)),
                ('image_path', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'blog_cards',
            },
        ),
    ]
